travis:
  secure:
    BINSTAR_TOKEN: RracBHxTDulrMJpe6kCB6fIqGmjBia+1FK5G4WWlohUGEiBcOqdFeZjGdbMc9lkhxCDzeG+AB8a8wFb2+Njmq8yiHhCUTSbmTqWg1hAXV5aFNT826YQPz8nN4HMoMxp/7YmaP4QkZXG7po8v2Zu/5i+4/uiOowCaOqEd/BdTRteu59lkqWgF7ZE2AOPVbOsy5cdIVpDgV1CCVGnv47pcnP11h5fNko9DCQBWEmqXkR9zVZAkyqpZ9Z3bwu10lPIBFC5LVWlo2f4ywadyXvVMHwpNu4hXJo+nYf0HqdCurzulViTS8s0A9dU7iiiSQhAgeNIZNBps2R0bsExx+2AteijgtrrWIaDhXDdFqeRjKFsKy0WZeAsVX0w8wV3o3fDVM+pN7OJTag6e51vynUXN2+BwQ91QR6GocbRG7Nx2dNgWBVPTz6xzIL1/NY3qHBs8Zl5uZ+klFketDIOg1VbLUi0IgoF3A+4saGXfl+WmQnZEJmykavn4NHUUdAuot7+9uplNjuJC8c48tdi8Q1yQdQgQ8570AeecxpceuY83PRveCKUomLSsTWT21bXjHHQ/B/rDvGVOgeMXUjZ64nbL4zQlNWYuJ7ZXz5U3uZP1CyLXsT8lylUoDv7tBdcMNk9c9k25glbtC3Cd9Y1PkqK3Vk+FxXxy33LQzWOpYAgEyNU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
